 version: "3.9"

 services:
  
  # nginx
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - mysql
      - php

  # mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: always
    volumes:
      - ./db/backup:/var/lib/mysql
    env_file:
      - ./db/env/dev_env

  # php
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql