# api version of deployment is apps/v1
# try >> kubectl api-resources | grep deployments
apiVersion: apps/v1

# kind of that yml file
kind: Deployment

# meta data for this deployment
metadata:
  name: apache-deployment
  labels: 
    app: webserver

# define the spec of the replicas (replicas is responsible of creating pods by using the same template)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver

  # define the template 
  # labels: must have the same labels used by replicas to help replicas to select that templates
  template:
    metadata:
      labels:
        app: webserver

    # define the containers
    spec:
      containers: 
        - name: apacheweb-c
          image: bitnami/apache:latest
          ports:
            - containerPort: 80