pipeline {
    agent { 
        node {
            label 'linux-node'
            }
      }
    triggers {
        pollSCM '*/5 * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh 'sudo  echo "super hello world" '
                sh 'cd CI-CD/jenkins/myapp'
                sh 'which python3'
                sh 'which pip3'
                sh 'pip3 install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                cd CI-CD/jenkins/myapp
                python3 hello.py
                python3 hello.py --name=Brad
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}