# api version of deployment is apps/v1
# try >> kubectl api-resources | grep deployments
apiVersion: apps/v1

# kind of that yml file
kind: Deployment

# meta data for this deployment
metadata:
  name: dep-nodeapp

# define the spec of the replicas (replicas is responsible of creating pods by using the same template)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp

  # define the template 
  # labels: must have the same labels used by replicas to help replicas to select that templates
  template:
    metadata:
      labels:
        app: nodeapp

    # define the containers
    spec:
      containers: 
        - name: nodeapp-c
          image: ahmedmohamed1993/first-app:v2
          ports:
            - containerPort: 4000