# api version of deployment is apps/v1
# try >> kubectl api-resources | grep deployments
apiVersion: apps/v1

kind: Deployment

metadata:
  name: node-web-app

# define the spec of the replicas (replicas is responsible of creating pods by using the same template)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app

  # define the template 
  # replicas will build the template
  # to help replicas found the template to build 
  # labels: must have the same labels used by replicas to help replicas  select that templates
  template:
    metadata:
      labels:
        app: node-app

    # define the containers
    spec:
      containers: 
        - name: web
          image: ahmedmohamed1993/node-app:v1
          ports:
            - containerPort: 4000